export const SEARCH_CONFIG = {
  DEBOUNCE_DELAY: 500,
  RESULTS_PER_PAGE: 10,
  REQUEST_TIMEOUT: 10000,
  CACHE_TTL: 5 * 60 * 1000, // 5 minutes
  MAX_CACHE_SIZE: 50,
} as const;

export const PRODUCT_CATEGORIES = [
  'Electronics',
  'Accessories',
  'Audio',
  'Wearables',
  'Gaming',
  'Home & Office',
] as const;

export const PRODUCT_NAMES = {
  Electronics: [
    'Wireless Bluetooth Headphones',
    'USB-C Hub Adapter',
    'Mechanical Keyboard',
    'Portable SSD 1TB',
    '4K Webcam',
    'Smart LED Monitor',
    'Wireless Mouse',
    'Laptop Stand',
    'Power Bank 20000mAh',
    'USB Microphone',
  ],
  Accessories: [
    'Phone Case Premium',
    'Screen Protector Pack',
    'Charging Cable Braided',
    'Laptop Sleeve',
    'Cable Organizer Kit',
    'Webcam Cover Slider',
    'Keyboard Wrist Rest',
    'Monitor Light Bar',
    'Desk Mat XL',
    'Phone Stand Adjustable',
  ],
  Audio: [
    'True Wireless Earbuds',
    'Noise Cancelling Headphones',
    'Bluetooth Speaker',
    'Studio Headphones',
    'Soundbar Compact',
    'Podcast Microphone Kit',
    'DAC Amplifier',
    'Earphone Case',
    'Audio Splitter',
    'Microphone Arm Stand',
  ],
  Wearables: [
    'Smartwatch Pro',
    'Fitness Tracker Band',
    'Smart Ring',
    'VR Headset Lite',
    'Smart Glasses',
    'Health Monitor Watch',
    'Activity Tracker Kids',
    'Sleep Tracker',
    'Posture Corrector Smart',
    'UV Monitor Band',
  ],
  Gaming: [
    'Gaming Mouse RGB',
    'Controller Wireless',
    'Gaming Headset 7.1',
    'Capture Card 4K',
    'Stream Deck',
    'Gaming Keyboard TKL',
    'Mouse Pad XXL',
    'Controller Grip Kit',
    'Gaming Chair',
    'RGB Light Strip',
  ],
  'Home & Office': [
    'Smart Plug WiFi',
    'LED Desk Lamp',
    'Air Quality Monitor',
    'Smart Thermostat',
    'Video Doorbell',
    'WiFi Extender',
    'Paper Shredder',
    'Label Maker',
    'Document Scanner',
    'Ergonomic Footrest',
  ],
} as const;
